### ISSUE TITLE
It should not unset attributes if SP comes with unknown entityCategory

### ISSUE THREAD

**Issue by sitya** [simplesamlphp/simplesamlphp-module-entitycategories#1]
Hi Jaime,

I found a scenario with working this module, which is too strict, at least it does not fit into federation practice. For example: I set up our IdP to handle R&S entityCategory as it is expected, but if an SP comes with some other entityCategory which is not mentioned in the entityCategory module's config, **all required attributes will be unset**. I think, the module should deal with only the matched (IdP-config - SP metadata) entityCategories, and leave attributes untouched if "unknown" entity category comes from the SP's metadata.

What do you think?

cheers,
Tamas

---

Btw: it is not working at all with older simpleSAMLphp because of namespaces.[ I modified it a bit](https://github.com/sitya/simplesamlphp-module-entitycategories/commit/351ba9a1ab03a11488f21b10f14bdfd48f8f508f) to be compatibile with 14.x.

**Comment by sitya** [comment]
Hi,

I have implemented some addtional options:
* `strict`: allow to release attributes to entities having unknown entity category based on requested attributes
* `allowRequestedAttributes`: allow to release additional requested attributes than configured in the list of the configuration of an entity category.

Default values are set that these options do not change the default behave of the module.

I have not made a pull request because I use the modul with 1.14.13, without namespaces.

Anyway: https://github.com/sitya/simplesamlphp-module-entitycategories/commits/master

cheers, Tamas

**Comment by jaimeperez** [comment]
Hi @sitya!

I understand that with the changes merged in #2, this is resolved, right?

**Comment by sitya** [comment]
Yes, thanks.
